[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx tsx src/database/migrate.ts && node dist/index.js"
