-- Add authentication fields
ALTER TABLE patients ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS refresh_token_hash VARCHAR(255);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS login_attempts INTEGER DEFAULT 0;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

ALTER TABLE doctors ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS refresh_token_hash VARCHAR(255);
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_patients_email ON patients(email);
CREATE INDEX IF NOT EXISTS idx_doctors_email ON doctors(email);
